name: guju_calendar2
description: A new Flutter application.

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  table_calendar: ^3.1.2
  intl: ^0.18.1
  google_fonts: ^6.1.0
  flutter_local_notifications: ^18.0.1
  url_launcher: ^6.2.6
  share_plus: ^7.2.1

dependency_overrides:
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
