name: guju_calendar
description: Guju Calendar App
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  firebase_core: ^2.18.0
  firebase_auth: ^4.6.0
  cloud_firestore: ^4.9.0
  google_mobile_ads: ^3.0.0
  table_calendar: ^3.0.9
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  google_fonts: ^6.1.0
  flutter_local_notifications: ^9.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
